version: '3.4'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
     - ./db-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example

  api:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__Main: "server=db;port=3306;user=root;password=example;database=LocationLog;"

volumes:
 db-data:      
      